### ISSUE TITLE
Can go to dashboard without sigining in, and signed in as someone else???

### ISSUE THREAD

**Issue by buenoluis007** [CSC59939/studybuddys#69]
I'm able to go to the dashboard without signing in, and who is this gerry person? Also all these ghost courses exists.

![image](https://user-images.githubusercontent.com/33500965/48523555-e743bc00-e84a-11e8-8cbe-6945bd347140.png)

**Comment by MelvinTham** [comment]
Sorry, we are currently working on this issue. We will find out who this "Gerry" person is.

**Comment by mjacome0** [comment]
Fixed. You are your own person now.
